import * as THREE from "three";

const VERSION="football-realism-v5-20260822";
const TYPO=Object.freeze({
  "uefa-2026":{label:"UEFA 2026",font:"condensed",target:{name:7,back:30,front:12},name:{x:50,y:20,scale:30,rotation:0},back:{x:50,y:55,scale:50,rotation:0},front:{x:50,y:48,scale:20,rotation:0}},
  "europe-1990s":{label:"Europa anni 90",font:"impact",target:{name:6.5,back:29,front:11},name:{x:50,y:21,scale:32,rotation:0},back:{x:50,y:55,scale:49,rotation:0},front:{x:50,y:48,scale:19,rotation:0}},
  "europe-modern":{label:"Europa 2010–2026",font:"geometric",target:{name:6.8,back:31,front:12},name:{x:50,y:19,scale:29,rotation:0},back:{x:50,y:54,scale:51,rotation:0},front:{x:50,y:47,scale:20,rotation:0}}
});
const COLLARS=Object.freeze({original:"Originale mesh",crew:"Crew / tondo rib",v:"V-neck rib",polo:"Polo fold-over",button:"Polo con bottone",split:"Split V / retro",retro:"Anni 90 largo",hybrid:"2010–2026 hybrid"});
const PLACE=Object.freeze({
  crest:{label:"Crest squadra",surface:"shirt-front",x:38,y:29,scale:13,src:"UEFA 2026 art.14"},
  brand:{label:"Brand / manufacturer",surface:"shirt-front",x:62,y:29,scale:10,src:"UEFA 2026 art.22"},
  sponsor:{label:"Main sponsor",surface:"shirt-front",x:50,y:53,scale:31,src:"UEFA 2026 art.28"},
  "sleeve-patch":{label:"Sleeve patch",surface:"left-sleeve",x:50,y:40,scale:18,src:"UEFA sleeve free zone"},
  "competition-badge":{label:"Competition badge",surface:"right-sleeve",x:50,y:34,scale:19,src:"UEFA 2026 art.36–37"},
  commemorative:{label:"Commemorative badge",surface:"shirt-front",x:50,y:24,scale:11,src:"UEFA 2026 art.34"}
});
const FONT={impact:["Impact,Haettenschweiler,'Arial Narrow Bold',sans-serif",900],condensed:["'Arial Narrow','Helvetica Neue Condensed',Arial,sans-serif",900],geometric:["Futura,Avenir,'Century Gothic',Arial,sans-serif",800]};
const realism={version:VERSION,typography:"uefa-2026",collar:"original",collarColor:"#9bbcf0",boots:true,bootColor:"#111827",bootAccent:"#9bbcf0",crestInNumber:false,placementStandard:"uefa-europe-1990-2026"};
let api,state,scene,shirt,socks,collarGroup,lowerGroup,crestGroup,raycaster=new THREE.Raycaster(),queued=false;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,Number(v)||0));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const box=o=>new THREE.Box3().setFromObject(o);
function disposeGroup(g){if(!g)return;for(const o of [...g.children]){g.remove(o);o.traverse?.(n=>{n.geometry?.dispose?.();if(n.material){for(const m of Array.isArray(n.material)?n.material:[n.material]){m.map?.userData?.generated&&m.map.dispose?.();m.dispose?.();}}});}}
async function waitReady(){for(let i=0;i<400;i++){if(window.__sportswear3d?.ready&&window.__footballRealismScene?.isScene)return;await new Promise(r=>setTimeout(r,50));}throw new Error("runtime 3D non pronto");}
function control(container,key,value){const el=document.querySelector(`#${container} input[data-key="${key}"]`);if(el){el.value=String(value);el.dispatchEvent(new Event("input",{bubbles:true}));}}
function applyTypography(id=realism.typography){const p=TYPO[id]||TYPO["uefa-2026"];realism.typography=TYPO[id]?id:"uefa-2026";state.personalization.font=p.font;const fs=document.getElementById("player-font");if(fs){fs.value=p.font;fs.dispatchEvent(new Event("change",{bubbles:true}));}for(const [c,v] of [["back-name-controls",p.name],["back-number-controls",p.back],["front-number-controls",p.front]])for(const [k,n] of Object.entries(v))control(c,k,n);const note=document.getElementById("football-typography-note");if(note)note.textContent=`Target fisico: nome ${p.target.name} cm · numero retro ${p.target.back} cm · frontale ${p.target.front} cm. X/Y/scala/rotazione restano liberi.`;schedule();}
function injectUi(){if(document.getElementById("football-realism-controls"))return;const panel=document.querySelector(".panel"),graphics=document.getElementById("graphics-list")?.closest("section");if(!panel)return;const s=document.createElement("section");s.id="football-realism-controls";s.innerHTML=`<header class="section-head"><h2>Football realism</h2><span>1990–2026/27</span></header><p class="help">Default da regolamenti UEFA e pattern europei reali. Gli override manuali esistenti restano attivi.</p><div class="subcard"><h3>Tipografia gara</h3><div class="fields two"><label>Preset<select id="football-typography">${Object.entries(TYPO).map(([k,v])=>`<option value="${k}">${esc(v.label)}</option>`).join("")}</select></label><label>Logo nel numero<select id="crest-in-number"><option value="off">No</option><option value="on">Sì — primo crest/logo</option></select></label></div><div class="inline-actions"><button id="apply-football-typography" type="button">Applica default realistici</button></div><p id="football-typography-note" class="help"></p></div><div class="subcard"><h3>Colletto</h3><div class="fields two"><label>Tipo<select id="football-collar">${Object.entries(COLLARS).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join("")}</select></label><label>Colore<input id="football-collar-color" type="color" value="#9bbcf0"></label></div></div><div class="subcard"><h3>Calzettoni completi + scarpette</h3><label class="check"><input id="football-boots" type="checkbox" checked> Mostra scarpette</label><div class="fields two"><label>Scarpette<input id="football-boot-color" type="color" value="#111827"></label><label>Dettaglio<input id="football-boot-accent" type="color" value="#9bbcf0"></label></div><p class="help">Default scuro + dettaglio azzurro coerente con la palette 2D corrente; colori sempre modificabili.</p></div><div class="subcard"><h3>Preset posizioni</h3><div class="add-row">${Object.entries(PLACE).map(([k,v])=>`<button type="button" data-place="${k}">+ ${esc(v.label)}</button>`).join("")}</div><p id="football-placement-note" class="help">Dopo il preset usa X, Y, rotazione e scala nella card esistente.</p></div>`;graphics?panel.insertBefore(s,graphics):panel.append(s);}
function mat(c,rough=.72){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:0,side:THREE.DoubleSide});}
function curveTube(points,radius,c){const path=new THREE.CatmullRomCurve3(points,false,"centripetal");return new THREE.Mesh(new THREE.TubeGeometry(path,32,radius,8,false),mat(c,.78));}
function rebuildCollar(){if(!collarGroup){collarGroup=new THREE.Group();collarGroup.name="football-realism-collar";scene.add(collarGroup);}disposeGroup(collarGroup);if(realism.collar==="original")return;const b=box(shirt),sz=b.getSize(new THREE.Vector3()),cx=(b.min.x+b.max.x)/2,y=b.max.y-sz.y*.075,z=b.max.z+sz.z*.015,rx=sz.x*.105,ry=sz.y*.038,r=Math.max(.015,sz.y*.009),c=realism.collarColor;let pts=[];if(realism.collar==="v"||realism.collar==="split"||realism.collar==="hybrid")pts=[new THREE.Vector3(cx-rx,y,z),new THREE.Vector3(cx,y-ry*1.7,z+.01),new THREE.Vector3(cx+rx,y,z)];else pts=[new THREE.Vector3(cx-rx,y,z),new THREE.Vector3(cx-rx*.7,y+ry,z),new THREE.Vector3(cx,y+ry*1.25,z),new THREE.Vector3(cx+rx*.7,y+ry,z),new THREE.Vector3(cx+rx,y,z)];collarGroup.add(curveTube(pts,r,c));if(["polo","button","retro"].includes(realism.collar)){for(const side of [-1,1]){const g=new THREE.Shape();g.moveTo(0,0);g.lineTo(side*rx*.95,-ry*.15);g.lineTo(side*rx*.55,-ry*1.7);g.lineTo(0,-ry*.75);g.closePath();const m=new THREE.Mesh(new THREE.ShapeGeometry(g),mat(c,.82));m.position.set(cx,y,z+.025);collarGroup.add(m);}if(realism.collar==="button"){for(let i=0;i<2;i++){const q=new THREE.Mesh(new THREE.SphereGeometry(r*.7,10,8),mat("#e6e6e6"));q.position.set(cx,y-ry*(.55+i*.55),z+.045);collarGroup.add(q);}}}if(realism.collar==="retro")collarGroup.scale.set(1.25,1.2,1);}
function roundedBox(w,h,d,c){const g=new THREE.BoxGeometry(w,h,d,3,2,4);const p=g.attributes.position;for(let i=0;i<p.count;i++){let x=p.getX(i),y=p.getY(i),z=p.getZ(i);if(z>0)x*=1.04;p.setXYZ(i,x,y,z);}g.computeVertexNormals();return new THREE.Mesh(g,mat(c,.62));}
function rebuildLower(){if(!lowerGroup){lowerGroup=new THREE.Group();lowerGroup.name="football-realism-lower";scene.add(lowerGroup);}disposeGroup(lowerGroup);if(!state.showSocks)return;const b=box(socks),sz=b.getSize(new THREE.Vector3()),cx=(b.min.x+b.max.x)/2,z=(b.min.z+b.max.z)/2,legX=sz.x*.21,ankleY=b.min.y-sz.y*.055,ankleH=Math.max(.13,sz.y*.18),bootW=sz.x*.34,bootH=Math.max(.12,sz.y*.12),bootD=Math.max(.38,sz.z*.72);for(const side of [-1,1]){const x=cx+side*legX;const ankle=new THREE.Mesh(new THREE.CapsuleGeometry(Math.max(.07,sz.x*.065),ankleH,5,12),mat(state.colors.socks,.86));ankle.position.set(x,ankleY,z);lowerGroup.add(ankle);if(realism.boots){const boot=roundedBox(bootW,bootH,bootD,realism.bootColor);boot.position.set(x,ankleY-ankleH*.65,z+bootD*.12);lowerGroup.add(boot);const stripe=roundedBox(bootW*.72,bootH*.08,bootD*.46,realism.bootAccent);stripe.position.set(x,boot.position.y+bootH*.52,boot.position.z+bootD*.08);lowerGroup.add(stripe);for(let s=-1;s<=1;s++)for(let f=0;f<2;f++){const stud=new THREE.Mesh(new THREE.CylinderGeometry(bootW*.035,bootW*.045,bootH*.22,8),mat("#20252c",.65));stud.position.set(x+s*bootW*.22,boot.position.y-bootH*.62,boot.position.z+(f?-.18:.22)*bootD);lowerGroup.add(stud);}}}}
function worldNormal(hit){return (hit.face?.normal?.clone()||new THREE.Vector3(0,0,-1)).transformDirection(hit.object.matrixWorld).normalize();}
function shirtHit(xPct,yPct){const b=box(shirt),sz=b.getSize(new THREE.Vector3()),x=THREE.MathUtils.lerp(b.min.x+sz.x*.16,b.max.x-sz.x*.16,clamp(xPct,0,100)/100),y=THREE.MathUtils.lerp(b.max.y-sz.y*.15,b.min.y+sz.y*.15,clamp(yPct,0,100)/100),origin=new THREE.Vector3(x,y,b.min.z-sz.z*4-2);raycaster.set(origin,new THREE.Vector3(0,0,1));const meshes=[];shirt.traverse(o=>{if(o.isMesh)meshes.push(o);});const hit=raycaster.intersectObjects(meshes,false)[0];if(!hit)return null;let n=worldNormal(hit);if(n.z>0)n.negate();return{p:hit.point.clone().add(n.clone().multiplyScalar(.014)),n};}
function crestTexture(){const g=state.graphics.find(x=>["crest","logo"].includes(x.type)&&x.texture?.image);if(!g)return null;const num=String(state.personalization.number||"10").slice(0,6),cv=document.createElement("canvas");cv.width=900;cv.height=900;const c=cv.getContext("2d"),f=FONT[state.personalization.font]||FONT.condensed;c.font=`${f[1]} 720px ${f[0]}`;c.textAlign="center";c.textBaseline="middle";c.fillStyle="#fff";c.fillText(num,450,455);c.globalCompositeOperation="source-in";const im=g.texture.image;const iw=im.width||512,ih=im.height||512,cell=220;for(let i=0;i<3;i++){const x=230+i*220,y=610,w=cell,h=cell*ih/iw;c.drawImage(im,x-w/2,y-h/2,w,h);}c.globalCompositeOperation="source-over";const t=new THREE.CanvasTexture(cv);t.colorSpace=THREE.SRGBColorSpace;t.userData.generated=true;return t;}
function rebuildCrest(){if(!crestGroup){crestGroup=new THREE.Group();crestGroup.name="football-realism-crest-number";scene.add(crestGroup);}disposeGroup(crestGroup);if(!realism.crestInNumber)return;const tex=crestTexture();if(!tex)return;const cfg=state.personalization.backNumber,spanX=clamp(cfg.scale,12,70)*.75,spanY=spanX*1.15,cols=8,rows=10,pos=[],uv=[],idx=[];for(let r=0;r<=rows;r++)for(let c=0;c<=cols;c++){const px=cfg.x+(c/cols-.5)*spanX,py=cfg.y+(r/rows-.5)*spanY,h=shirtHit(px,py);if(!h){tex.dispose();return;}pos.push(h.p.x,h.p.y,h.p.z);uv.push(1-c/cols,1-r/rows);}for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const a=r*(cols+1)+c,b=a+1,d=(r+1)*(cols+1)+c,e=d+1;idx.push(a,d,b,b,d,e);}const geo=new THREE.BufferGeometry();geo.setAttribute("position",new THREE.Float32BufferAttribute(pos,3));geo.setAttribute("uv",new THREE.Float32BufferAttribute(uv,2));geo.setIndex(idx);geo.computeVertexNormals();const m=new THREE.MeshStandardMaterial({map:tex,transparent:true,alphaTest:.015,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-6,roughness:.78,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geo,m);mesh.renderOrder=14;crestGroup.add(mesh);}
function baseButton(id){if(id==="sponsor")return document.getElementById("add-sponsor");if(id==="competition-badge")return document.getElementById("add-badge");if(id==="sleeve-patch"||id==="commemorative")return document.getElementById("add-patch");return document.getElementById("add-logo");}
function setCard(card,key,val){if(key==="surface"){const s=card?.querySelector('[data-field="surface"]');if(s){s.value=val;s.dispatchEvent(new Event("change",{bubbles:true}));}}else{const i=card?.querySelector(`input[data-key="${key}"]`);if(i){i.value=String(val);i.dispatchEvent(new Event("input",{bubbles:true}));}}}
function addPreset(id){const p=PLACE[id],bt=baseButton(id);if(!p||!bt)return;const before=state.graphics.length;bt.click();if(state.graphics.length<=before)return;const g=state.graphics.at(-1);Object.assign(g,{type:id,surface:p.surface,x:p.x,y:p.y,scale:p.scale,rotation:0});const card=document.querySelector(`[data-graphic="${g.id}"]`);if(card){const h=card.querySelector(".graphic-head strong");if(h)h.textContent=p.label;for(const [k,v] of Object.entries({surface:p.surface,x:p.x,y:p.y,scale:p.scale,rotation:0}))setCard(card,k,v);}const n=document.getElementById("football-placement-note");if(n)n.textContent=`${p.label}: ${p.src}. Override X/Y/rotazione/scala sempre disponibile.`;schedule();}
function augment(){const p=TYPO[realism.typography];return{version:VERSION,lower_body:{complete_socks:!!state.showSocks,boots_visible:realism.boots,boot_color:realism.bootColor,boot_accent:realism.bootAccent},typography:{preset:realism.typography,target_name_height_cm:p.target.name,target_back_number_height_cm:p.target.back,target_front_number_height_cm:p.target.front,crest_in_number:realism.crestInNumber},collar:{type:realism.collar,color:realism.collarColor},placement_standard:realism.placementStandard,placement_presets:PLACE,research_basis:{name:"UEFA 2026: nome sopra numero, lettere <=7.5cm",number:"UEFA 2026: retro uomini 25–35cm; target 30cm",crest:"petto sopra sponsor",manufacturer:"petto sopra sponsor",sponsor:"centro torso",crest_in_number:"precedente regolamentare UEFA: emblema club alla base delle cifre"}};}
function syncPayload(){const ta=document.getElementById("payload");if(!ta)return;try{const p=JSON.parse(ta.value);p.realism=augment();ta.value=JSON.stringify(p,null,2);window.__payload3d=p;}catch{}const sm=document.getElementById("summary");if(sm){let r=sm.querySelector("[data-football-realism]");if(!r){r=document.createElement("div");r.className="summary-row";r.dataset.footballRealism="1";r.innerHTML="<span>Football realism</span><span></span>";sm.append(r);}r.lastElementChild.textContent=`${COLLARS[realism.collar]} · boots ${realism.boots?"sì":"no"}`;}}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;rebuildCollar();rebuildLower();rebuildCrest();syncPayload();});}
function bind(){document.getElementById("apply-football-typography")?.addEventListener("click",()=>applyTypography(document.getElementById("football-typography").value));document.getElementById("crest-in-number")?.addEventListener("change",e=>{realism.crestInNumber=e.target.value==="on";schedule();});document.getElementById("football-collar")?.addEventListener("change",e=>{realism.collar=e.target.value;schedule();});document.getElementById("football-collar-color")?.addEventListener("input",e=>{realism.collarColor=e.target.value;schedule();});document.getElementById("football-boots")?.addEventListener("change",e=>{realism.boots=e.target.checked;schedule();});document.getElementById("football-boot-color")?.addEventListener("input",e=>{realism.bootColor=e.target.value;schedule();});document.getElementById("football-boot-accent")?.addEventListener("input",e=>{realism.bootAccent=e.target.value;schedule();});document.querySelectorAll("[data-place]").forEach(b=>b.addEventListener("click",()=>addPreset(b.dataset.place)));document.addEventListener("input",e=>{if(["player-number","player-font","print-color","socks-color"].includes(e.target?.id)||e.target?.matches?.("input[data-key]"))schedule();});document.addEventListener("change",e=>{if(e.target?.id==="show-socks"||e.target?.matches?.('[data-field="file"]'))setTimeout(schedule,80);});const gl=document.getElementById("graphics-list");if(gl)new MutationObserver(()=>setTimeout(schedule,0)).observe(gl,{childList:true,subtree:true});}
async function boot(){try{await waitReady();api=window.__sportswear3d;state=api.state;scene=window.__footballRealismScene;shirt=scene.getObjectByName("donor-shirt");socks=scene.getObjectByName("donor-socks");if(!shirt||!socks)throw new Error("donor mesh non trovate");realism.collarColor=state.colors.shirt;realism.bootAccent=state.colors.shirt;injectUi();const sc=document.getElementById("show-socks");if(sc&&!sc.checked){sc.checked=true;sc.dispatchEvent(new Event("change",{bubbles:true}));}bind();applyTypography("uefa-2026");const op=api.payload,od=api.diagnostics;api.payload=()=>({...op(),realism:augment()});api.diagnostics=()=>({...od(),football_realism:{version:VERSION,collar:realism.collar,boots:realism.boots,crest_in_number:realism.crestInNumber,collar_meshes:collarGroup?.children.length||0,lower_meshes:lowerGroup?.children.length||0,crest_number_meshes:crestGroup?.children.length||0}});api.realism=realism;api.version=`${api.version}+${VERSION}`;window.__footballRealismReady=true;schedule();}catch(e){console.error(e);window.__footballRealismError=String(e?.stack||e);}}
boot();
